---
- name: Terminate instances
  hosts: localhost
  connection: local
  vars:
    facts_dir: "{{ playbook_dir }}/facts"
    facts_file: "{{ facts_dir }}/ec2.yml"
  tasks:
    - name: get ec2 fact 
      include_vars: file="{{ facts_file }}" #name=instances
      when: ansible_version['full'] >= 2.2
      # free-form is for <= 2.2
    - name: get ec2 fact (old)
      include_vars: "{{ facts_file }}"
      when: ansible_version['full'] <= 2.2
    - name: debug
      debug: msg="{{instances}}" 
    - name: Terminate instances that currently running
      ec2:
        state: 'absent'
        instance_ids: '{{ item.id }}'
        region: '{{ item.region }}'
      with_items: "{{ instances }}"
    - name: Delete ec2 facts file after termination
      file: src="{{ facts_file }}" state=absent
